"""empty message

Revision ID: 13f22682473f
Revises: 8068d8349925
Create Date: 2019-02-11 22:39:03.597025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f22682473f'
down_revision = '8068d8349925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canteen', sa.Column('delete_time', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('delete_time', sa.Integer(), nullable=True))
    op.add_column('comment_image', sa.Column('delete_time', sa.Integer(), nullable=True))
    op.add_column('food', sa.Column('delete_time', sa.Integer(), nullable=True))
    op.add_column('image', sa.Column('delete_time', sa.Integer(), nullable=True))
    op.add_column('restaurant', sa.Column('delete_time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('delete_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'delete_time')
    op.drop_column('restaurant', 'delete_time')
    op.drop_column('image', 'delete_time')
    op.drop_column('food', 'delete_time')
    op.drop_column('comment_image', 'delete_time')
    op.drop_column('comment', 'delete_time')
    op.drop_column('canteen', 'delete_time')
    # ### end Alembic commands ###
