"""empty message

Revision ID: 605fa9165c86
Revises: 9f875b0208d0
Create Date: 2019-01-26 14:37:24.804180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605fa9165c86'
down_revision = '9f875b0208d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
