"""empty message

Revision ID: 67b9b939e09b
Revises: ec4a9fd9dcd9
Create Date: 2019-02-18 21:01:11.474984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67b9b939e09b'
down_revision = 'ec4a9fd9dcd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.String(length=100), nullable=True))
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
