"""empty message

Revision ID: 6d973d17f6c9
Revises: ad361c98d1d9
Create Date: 2019-03-07 12:58:07.117317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d973d17f6c9'
down_revision = 'ad361c98d1d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('canteen', 'campus_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'canteen', 'campus', ['campus_id'], ['id'])
    op.add_column('restaurant', sa.Column('location', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'location')
    op.drop_constraint(None, 'canteen', type_='foreignkey')
    op.alter_column('canteen', 'campus_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
