"""empty message

Revision ID: 8068d8349925
Revises: 8ccf037e1c1c
Create Date: 2019-02-10 15:39:34.946645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8068d8349925'
down_revision = '8ccf037e1c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_ibfk_2', 'image', type_='foreignkey')
    op.drop_constraint('image_ibfk_4', 'image', type_='foreignkey')
    op.drop_constraint('image_ibfk_5', 'image', type_='foreignkey')
    op.drop_constraint('image_ibfk_3', 'image', type_='foreignkey')
    op.drop_constraint('image_ibfk_1', 'image', type_='foreignkey')
    op.drop_column('image', 'comment_id')
    op.drop_column('image', 'restaurant_id')
    op.drop_column('image', 'user_id')
    op.drop_column('image', 'food_id')
    op.drop_column('image', 'canteen_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('canteen_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('image', sa.Column('food_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('image', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('image', sa.Column('restaurant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('image', sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('image_ibfk_1', 'image', 'user', ['user_id'], ['id'])
    op.create_foreign_key('image_ibfk_3', 'image', 'restaurant', ['restaurant_id'], ['id'])
    op.create_foreign_key('image_ibfk_5', 'image', 'comment', ['comment_id'], ['id'])
    op.create_foreign_key('image_ibfk_4', 'image', 'food', ['food_id'], ['id'])
    op.create_foreign_key('image_ibfk_2', 'image', 'canteen', ['canteen_id'], ['id'])
    # ### end Alembic commands ###
