"""empty message

Revision ID: 8ccf037e1c1c
Revises: 605fa9165c86
Create Date: 2019-01-26 23:25:05.658196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ccf037e1c1c'
down_revision = '605fa9165c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canteen', sa.Column('campus_id', sa.Integer(), nullable=False))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=24),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=24),
               nullable=False)
    op.drop_column('canteen', 'campus_id')
    # ### end Alembic commands ###
