"""empty message

Revision ID: ad361c98d1d9
Revises: 67b9b939e09b
Create Date: 2019-02-21 23:38:11.799257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad361c98d1d9'
down_revision = '67b9b939e09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canteen', sa.Column('image_amount', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('image_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'image_amount')
    op.drop_column('canteen', 'image_amount')
    # ### end Alembic commands ###
